controller_manager:
  ros__parameters:
    update_rate: 50

    diffdrive_controller:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

diffdrive_controller:
  ros__parameters:
    left_wheel_names: ["front left wheel", "back left wheel"]
    right_wheel_names: ["front right wheel", "back right wheel"]

    wheel_separation: 0.381 # https://www.generationrobots.com/media/Pioneer3AT-P3AT-RevA-datasheet.pdf
    wheels_per_side: 2
    wheel_radius: 0.111 # Cylinder { height 0.095 radius 0.11

    # The real separation between wheels is not resulting in a perfect odometry
    wheel_separation_multiplier: 1.0

    use_stamped_vel: false
    base_frame_id: "base_link"

# joint_state_broadcaster:
#   ros__parameters:
#     extra_joints:
#       - CASTER_WHEEL_FRONT_LEFT_JOINT
#       - CASTER_WHEEL_FRONT_RIGHT_JOINT
#       - CASTER_WHEEL_BACK_LEFT_JOINT
#       - CASTER_WHEEL_BACK_RIGHT_JOINT
#       - SMALL_WHEEL_JOINT
#       - SMALL_WHEEL_JOINT_0
#       - SMALL_WHEEL_JOINT_1
#       - SMALL_WHEEL_JOINT_2
#       - head_1_joint
#       - head_2_joint
#       - torso_lift_joint
